export const messages = {
  en: {
    "Peaceful settlement of the question of Palestine :":
      "Peaceful settlement of the question of Palestine",
    "Division for Palestinian Rights of the Secretariat :":
      "Division for Palestinian Rights of the Secretariat",
    "Committee on the Exercise of the Inalienable Rights of the Palestinian People :":
      "Committee on the Exercise of the Inalienable Rights of the Palestinian People",
    "Special information programme on the question of Palestine of the Department of Global Communications of the Secretariat :":
      "Special information programme on the question of Palestine of the Department of Global Communications of the Secretariat",
    "Special information programme on the question of Palestine of the Department of Public Information of the Secretariat :":
      "Special information programme on the question of Palestine of the Department of Public Information of the Secretariat",
    "Jerusalem :": "Jerusalem",
    "Department of Public Information of the Secretariat :":
      "Department of Public Information of the Secretariat",
    "Question of Palestine :": "Question of Palestine",
    "The uprising (intifadah) of the Palestinian people :":
      "The uprising (intifadah) of the Palestinian people",
    "International Peace Conference on the Middle East :":
      "International Peace Conference on the Middle East",
    AFG: "AFGHANISTAN",
    ALB: "ALBANIA",
    DZA: "ALGERIA",
    AND: "ANDORRA",
    AGO: "ANGOLA",
    ATG: "ANTIGUA AND BARBUDA",
    ARG: "ARGENTINA",
    ARM: "ARMENIA",
    AUS: "AUSTRALIA",
    AUT: "AUSTRIA",
    AZE: "AZERBAIJAN",
    BHS: "BAHAMAS",
    BHR: "BAHRAIN",
    BGD: "BANGLADESH",
    BRB: "BARBADOS",
    BLR: "BELARUS",
    BEL: "BELGIUM",
    BLZ: "BELIZE",
    BEN: "BENIN",
    BTN: "BHUTAN",
    BOL: "BOLIVIA (PLURINATIONAL STATE OF)",
    BIH: "BOSNIA AND HERZEGOVINA",
    BWA: "BOTSWANA",
    BRA: "BRAZIL",
    BRN: "BRUNEI DARUSSALAM",
    BGR: "BULGARIA",
    BFA: "BURKINA FASO",
    BDI: "BURUNDI",
    CPV: "CABO VERDE",
    KHM: "CAMBODIA",
    CMR: "CAMEROON",
    CAN: "CANADA",
    CAF: "CENTRAL AFRICAN REPUBLIC",
    TCD: "CHAD",
    CHL: "CHILE",
    CHN: "CHINA",
    COL: "COLOMBIA",
    COM: "COMOROS",
    COG: "CONGO",
    CRI: "COSTA RICA",
    CIV: 'COTE D"IVOIRE',
    HRV: "CROATIA",
    CUB: "CUBA",
    CYP: "CYPRUS",
    CZE: "CZECHIA",
    PRK: 'DEMOCRATIC PEOPLE"S REPUBLIC OF KOREA',
    COD: "DEMOCRATIC REPUBLIC OF THE CONGO",
    DNK: "DENMARK",
    DJI: "DJIBOUTI",
    DMA: "DOMINICA",
    DOM: "DOMINICAN REPUBLIC",
    ECU: "ECUADOR",
    EGY: "EGYPT",
    SLV: "EL SALVADOR",
    GNQ: "EQUATORIAL GUINEA",
    ERI: "ERITREA",
    EST: "ESTONIA",
    SWZ: "ESWATINI",
    ETH: "ETHIOPIA",
    FJI: "FIJI",
    FIN: "FINLAND",
    FRA: "FRANCE",
    GAB: "GABON",
    GMB: "GAMBIA",
    GEO: "GEORGIA",
    DEU: "GERMANY",
    GHA: "GHANA",
    GRC: "GREECE",
    GRD: "GRENADA",
    GTM: "GUATEMALA",
    GIN: "GUINEA",
    GNB: "GUINEA-BISSAU",
    GUY: "GUYANA",
    HTI: "HAITI",
    HND: "HONDURAS",
    HUN: "HUNGARY",
    ISL: "ICELAND",
    IND: "INDIA",
    IDN: "INDONESIA",
    IRN: "IRAN (ISLAMIC REPUBLIC OF)",
    IRQ: "IRAQ",
    IRL: "IRELAND",
    ISR: "ISRAEL",
    ITA: "ITALY",
    JAM: "JAMAICA",
    JPN: "JAPAN",
    JOR: "JORDAN",
    KAZ: "KAZAKHSTAN",
    KEN: "KENYA",
    KIR: "KIRIBATI",
    KWT: "KUWAIT",
    KGZ: "KYRGYZSTAN",
    LAO: 'LAO PEOPLE"S DEMOCRATIC REPUBLIC',
    LVA: "LATVIA",
    LBN: "LEBANON",
    LSO: "LESOTHO",
    LBR: "LIBERIA",
    LBY: "LIBYA",
    LIE: "LIECHTENSTEIN",
    LTU: "LITHUANIA",
    LUX: "LUXEMBOURG",
    MDG: "MADAGASCAR",
    MWI: "MALAWI",
    MYS: "MALAYSIA",
    MDV: "MALDIVES",
    MLI: "MALI",
    MLT: "MALTA",
    MHL: "MARSHALL ISLANDS",
    MRT: "MAURITANIA",
    MUS: "MAURITIUS",
    MEX: "MEXICO",
    FSM: "MICRONESIA (FEDERATED STATES OF)",
    MCO: "MONACO",
    MNG: "MONGOLIA",
    MNE: "MONTENEGRO",
    MAR: "MOROCCO",
    MOZ: "MOZAMBIQUE",
    MMR: "MYANMAR",
    NAM: "NAMIBIA",
    NRU: "NAURU",
    NPL: "NEPAL",
    NLD: "NETHERLANDS",
    NZL: "NEW ZEALAND",
    NIC: "NICARAGUA",
    NER: "NIGER",
    NGA: "NIGERIA",
    MKD: "NORTH MACEDONIA",
    NOR: "NORWAY",
    OMN: "OMAN",
    PAK: "PAKISTAN",
    PLW: "PALAU",
    PAN: "PANAMA",
    PNG: "PAPUA NEW GUINEA",
    PRY: "PARAGUAY",
    PER: "PERU",
    PHL: "PHILIPPINES",
    POL: "POLAND",
    PRT: "PORTUGAL",
    QAT: "QATAR",
    KOR: "REPUBLIC OF KOREA",
    MDA: "REPUBLIC OF MOLDOVA",
    ROU: "ROMANIA",
    RUS: "RUSSIAN FEDERATION",
    RWA: "RWANDA",
    KNA: "SAINT KITTS AND NEVIS",
    LCA: "SAINT LUCIA",
    VCT: "SAINT VINCENT AND THE GRENADINES",
    WSM: "SAMOA",
    SMR: "SAN MARINO",
    STP: "SAO TOME AND PRINCIPE",
    SAU: "SAUDI ARABIA",
    SEN: "SENEGAL",
    SRB: "SERBIA",
    SYC: "SEYCHELLES",
    SLE: "SIERRA LEONE",
    SGP: "SINGAPORE",
    SVK: "SLOVAKIA",
    SVN: "SLOVENIA",
    SLB: "SOLOMON ISLANDS",
    SOM: "SOMALIA",
    ZAF: "SOUTH AFRICA",
    SSD: "SOUTH SUDAN",
    ESP: "SPAIN",
    LKA: "SRI LANKA",
    SDN: "SUDAN",
    SUR: "SURINAME",
    SWE: "SWEDEN",
    CHE: "SWITZERLAND",
    SYR: "SYRIAN ARAB REPUBLIC",
    TJK: "TAJIKISTAN",
    THA: "THAILAND",
    TLS: "TIMOR-LESTE",
    TGO: "TOGO",
    TON: "TONGA",
    TTO: "TRINIDAD AND TOBAGO",
    TUN: "TUNISIA",
    TKM: "TURKMENISTAN",
    TUV: "TUVALU",
    TUR: "TURKIYE",
    UGA: "UGANDA",
    UKR: "UKRAINE",
    ARE: "UNITED ARAB EMIRATES",
    GBR: "UNITED KINGDOM",
    TZA: "UNITED REPUBLIC OF TANZANIA",
    USA: "UNITED STATES",
    URY: "URUGUAY",
    UZB: "UZBEKISTAN",
    VUT: "VANUATU",
    VEN: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    VNM: "VIET NAM",
    YEM: "YEMEN",
    ZMB: "ZAMBIA",
    ZWE: "ZIMBABWE",
    SCG: "SERBIA AND MONTENEGRO",
    YUG: "YUGOSLAVIA",
    CSK: "CZECHOSLOVAKIA",
    SUN: "USSR",
    YMD: "DEMOCRATIC YEMEN",
    DDR: "GERMAN DEMOCRATIC REPUBLIC",
    GER: "GERMANY, FEDERAL REPUBLIC OF",
    descrition: "descrition",
    "The uprising (intifadah) of the Palestinian People :":
      "The uprising (intifadah) of the Palestinian People",
    "Israeli settlement activities in the occupied Palestinian territory, in particular in occupied East Jerusalem :":
      "Israeli settlement activities in the occupied Palestinian territory, in particular in occupied East Jerusalem",
    "Special information programme on the question of Palestine :":
      "Special information programme on the question of Palestine",
    "Participation of Palestine in the work of the United Nations :":
      "Participation of Palestine in the work of the United Nations",
    "Special information programme of the question of Palestine of the Department of Public Information of the Secretariat :":
      "Special information programme of the question of Palestine of the Department of Public Information of the Secretariat",
    "Committee on the Exercise of the Inalienable Rights of the Palestinian people :":
      "Committee on the Exercise of the Inalienable Rights of the Palestinian people",
    "Special information programme on the question of Palestine of the Department of of Public Information of the Secretariat :":
      "Special information programme on the question of Palestine of the Department of of Public Information of the Secretariat",
    "Committee on the Exercise of Inalienable Rights of the Palestinian People :":
      "Committee on the Exercise of Inalienable Rights of the Palestinian People",
    "Peaceful settlement of the Question of Palestine :":
      "Peaceful settlement of the Question of Palestine",
    "Special Information Programme on the Question of Palestine of the Department of Public Information of the Secretariat :":
      "Special Information Programme on the Question of Palestine of the Department of Public Information of the Secretariat",
    "Special Information Programme on question of Palestine of the Department of Public Information of the Secretariat :":
      "Special Information Programme on question of Palestine of the Department of Public Information of the Secretariat",
    "Status of Palestine in the United Nations :":
      "Status of Palestine in the United Nations",
    "Pro Israel Votes": 'Pro Israel Votes',
    "Anti-Israel votes":'Anti-Israel votes',
    "Neutral votes":"Neutral votes",
    "List of countries":"List of countries",
    "Date of last vote":"Date of last vote",
    "In the last vote the state":"In the last vote the state",
    " voted against Israel":" voted against Israel",
    " avoided":" avoided",
    " voted for Israel": " voted for Israel",
    "Summary charts":"Summary charts",
    "About":"About",
    "Pro Israel":"Pro Israel",
    "Anti-Israel":"Anti-Israel",
    "Neutral":"Neutral",
    "Votes":"Votes",
    "history by date1":"",
    "history by date2":"'s vote history by date",
    'trnslate':'עב',
    'Sort by support for Israel':'Sort by support for Israel',
    'Sort by thousand byte':'Sort by support for Israel',
    about1: 'Working method',
    about2: 'I took from the UN website the list of votes according to the "Palestine" filter. The list of votes are:',
    about3: `I did not take the votes of the Security Council, but only votes open to all countries, because the purpose of the project is to show Israel's status and friendship with the various countries, and not with the individual members of the Security Council.`,
    about4: `I started from the premise that Israel always votes for itself, therefore the definition of voting for Israel is to vote like Israel. Each country has 5 options in each vote - yes, no, and neutral. Each of them is an active vote. And also a country that does not exist like East Germany, which is not counted, and another possibility of a country that exists but does not vote. For example, Afghanistan is in this position right now, and I treat it like a country that doesn't exist.`,
    about5: 'contact',
    about6: 'My name is Avraham Ben Arosh',
    about7: 'Email: ',
    about8: 'LinkedIn: '

  },
  he: {
    "Peaceful settlement of the question of Palestine :":
      "הסדר השלום של שאלת פלסטין",
    "Division for Palestinian Rights of the Secretariat :":
      "האגף לזכויות פלסטינים של המזכירות",
    "Committee on the Exercise of the Inalienable Rights of the Palestinian People :":
      "הוועדה למימוש הזכויות הבלתי ניתנות לביטול של העם הפלסטיני",
    "Special information programme on the question of Palestine of the Department of Global Communications of the Secretariat :":
      "תוכנית מידע מיוחדת בשאלת פלסטין של המחלקה לתקשורת גלובלית של המזכירות",
    "Special information programme on the question of Palestine of the Department of Public Information of the Secretariat :":
      "תוכנית מידע מיוחדת בשאלת פלסטין של המחלקה להסברה של המזכירות",
    "Jerusalem :": "ירושלים",
    "Department of Public Information of the Secretariat :":
      "המחלקה למידע ציבורי של המזכירות",
    "Question of Palestine :": "שאלת פלסטין",
    "The uprising (intifadah) of the Palestinian people :":
      "התקוממות (אינתיפאדה) של העם הפלסטיני",
    "International Peace Conference on the Middle East :":
      "ועידת השלום הבינלאומית על המזרח התיכון",
    AFG: "אפגניסטן",
    ALB: "אלבניה",
    DZA: "אלג'יריה",
    AND: "אנדורה",
    AGO: "אנגולה",
    ATG: "אנטיגואה וברבודה",
    ARG: "ארגנטינה",
    ARM: "ארמניה",
    AUS: "אוסטרליה",
    AUT: "אוסטריה",
    AZE: "אזרבייג'אן",
    BHS: "בהאמה",
    BHR: "באהרין",
    BGD: "בנגלדש",
    BRB: "ברבדוס",
    BLR: "בלארוס",
    BEL: "בלגיה",
    BLZ: "בליז",
    BEN: "בנין",
    BTN: "בהוטן",
    BOL: "בוליביה",
    BIH: "בוסניה והרצגובינה",
    BWA: "בוטסואנה",
    BRA: "ברזיל",
    BRN: "ברוניי דרוססלאם",
    BGR: "בולגריה",
    BFA: "בורקינה פאסו",
    BDI: "בורונדי",
    CPV: "כף ורדה",
    KHM: "קמבודיה",
    CMR: "קמרון",
    CAN: "קנדה",
    CAF: "רפובליקה מרכז אפריקאית",
    TCD: "צ'אד",
    CHL: "צ'ילה",
    CHN: "סין",
    COL: "קולומביה",
    COM: "קומורו",
    COG: "קונגו",
    CRI: "קוסטה ריקה",
    CIV: "חוף השנהב",
    HRV: "קרואטיה",
    CUB: "קובה",
    CYP: "קפריסין",
    CZE: "צ'כיה",
    PRK: "צפון קוריאה",
    COD: "הרפובליקה הדמוקרטית של קונגו",
    DNK: "דנמרק",
    DJI: "ג'יבוטי",
    DMA: "דומיניקה",
    DOM: "הרפובליקה הדומיניקנית",
    ECU: "אקוודור",
    EGY: "מצרים",
    SLV: "אל סלבדור",
    GNQ: "גינאה המשוונית",
    ERI: "אריטרה",
    EST: "אסטוניה",
    SWZ: "אסוואטיני",
    ETH: "אתיופיה",
    FJI: "פיג'י",
    FIN: "פינלנד",
    FRA: "צרפת",
    GAB: "גאבון",
    GMB: "גמביה",
    GEO: "ג'ורג'יה",
    DEU: "גרמניה",
    GHA: "ג'אנה",
    GRC: "יוון",
    GRD: "גרנדה",
    GTM: "גואטמלה",
    GIN: "גינאה",
    GNB: "גינאה-ביסאו",
    GUY: "גיאנה",
    HTI: "האיטי",
    HND: "הונדורס",
    HUN: "הונגריה",
    ISL: "איסלנד",
    IND: "הודו",
    IDN: "אינדונזיה",
    IRN: "איראן",
    IRQ: "איראק",
    IRL: "אירלנד",
    ISR: "ישראל",
    ITA: "איטליה",
    JAM: "ג'מייקה",
    JPN: "יפן",
    JOR: "ירדן",
    KAZ: "קזחסטן",
    KEN: "קניה",
    KIR: "קיריבטי",
    KWT: "כווית",
    KGZ: "קירגיזסטן",
    LAO: "הרפובליקה הדמוקרטית הדמוקרטית של לאו",
    LVA: "לטביה",
    LBN: "לבנון",
    LSO: "לסותו",
    LBR: "ליבריה",
    LBY: "לוב",
    LIE: "ליכטנשטיין",
    LTU: "ליטא",
    LUX: "לוקסמבורג",
    MDG: "מדגסקר",
    MWI: "מלווי",
    MYS: "מלזיה",
    MDV: "המלדיביים",
    MLI: "מאלי",
    MLT: "מלטה",
    MHL: "איי מרשל",
    MRT: "מאוריטניה",
    MUS: "מאוריטיוס",
    MEX: "מקסיקו",
    FSM: "מיקרונזיה",
    MCO: "מונאקו",
    MNG: "מונגוליה",
    MNE: "מונטנגרו",
    MAR: "מרוקו",
    MOZ: "מוזמביק",
    MMR: "מיאנמר",
    NAM: "נמיביה",
    NRU: "נאורו",
    NPL: "נפאל",
    NLD: "הולנד",
    NZL: "ניו זילנד",
    NIC: "ניקרגואה",
    NER: "ניגר",
    NGA: "ניגריה",
    MKD: "צפון מקדוניה",
    NOR: "נורווגיה",
    OMN: "אומן",
    PAK: "פקיסטן",
    PLW: "פלאו",
    PAN: "פנמה",
    PNG: "פאפואה גינאה החדשה",
    PRY: "פרגוואי",
    PER: "פרו",
    PHL: "פיליפינים",
    POL: "פולין",
    PRT: "פורטוגל",
    QAT: "קטאר",
    KOR: "דקום קוריאה",
    MDA: "מולדובה",
    ROU: "רומניה",
    RUS: "רוסיה",
    RWA: "רואנדה",
    KNA: "סנט קיטס ונביס",
    LCA: "סנט לוסיה",
    VCT: "סנט וינסנט והגרנדינים",
    WSM: "סמואה",
    SMR: "סן מרינו",
    STP: "סאו טומה ופרינסיפ",
    SAU: "ערב הסעודית",
    SEN: "סנגאל",
    SRB: "סרביה",
    SYC: "סיישל",
    SLE: "סיירה לאונה",
    SGP: "סינגפור",
    SVK: "סלובקיה",
    SVN: "סלובניה",
    SLB: "איי שלמה",
    SOM: "סומליה",
    ZAF: "דרום אפריקה",
    SSD: "דרום סודן",
    ESP: "ספרד",
    LKA: "סרי לנקה",
    SDN: "סודאן",
    SUR: "סורינאם",
    SWE: "שבדיה",
    CHE: "שוויץ",
    SYR: "סוריה",
    TJK: "טג'יקיסטן",
    THA: "תאילנד",
    TLS: "טימור-לסטה",
    TGO: "טוגו",
    TON: "טונגה",
    TTO: "טרינידד וטובגו",
    TUN: "תוניסיה",
    TKM: "טורקמניסטן",
    TUV: "טובאלו",
    TUR: "טורקיה",
    UGA: "אוגנדה",
    UKR: "אוקראינה",
    ARE: "איחוד האמירויות",
    GBR: "בריטניה",
    TZA: "טנזניה",
    USA: "ארצות הברית",
    URY: "אורוגוואי",
    UZB: "אוזבקיסטן",
    VUT: "וואנואטו",
    VEN: "ונצואלה",
    VNM: "ויאט נאם",
    YEM: "תימן",
    ZMB: "זמביה",
    ZWE: "זימבאבווה",
    SCG: "סרביה ומונטנגרו",
    YUG: "יוגוסלביה",
    CSK: "צ'כוסלובקיה",
    SUN: "ברית המועצות",
    YMD: "תימן הדמוקרטית",
    DDR: "מזרח גרמניה",
    GER: "מערב גרמניה",
    descrition: "תיאור",
    "The uprising (intifadah) of the Palestinian People :":
      "המרד (אינתיפאדה) של העם הפלסטיני",
    "Israeli settlement activities in the occupied Palestinian territory, in particular in occupied East Jerusalem :":
      "פעילות ההתנחלות הישראלית בשטח הפלסטיני הכבוש, במיוחד במזרח ירושלים הכבושה",
    "Special information programme on the question of Palestine :":
      "תוכנית מידע מיוחדת בשאלת פלסטין",
    "Participation of Palestine in the work of the United Nations :":
      "השתתפות פלסטין בעבודת האו\"ם",
    "Special information programme of the question of Palestine of the Department of Public Information of the Secretariat :":
      "תכנית הסברה מיוחדת לשאלת פלסטין של המחלקה להסברה של המזכירות",
    "Committee on the Exercise of the Inalienable Rights of the Palestinian people :":
      "הוועדה למימוש הזכויות הבלתי ניתנות לביטול של העם הפלסטיני",
    "Special information programme on the question of Palestine of the Department of of Public Information of the Secretariat :":
      "תכנית הסברה מיוחדת בשאלת פלסטין של המחלקה להסברה של המזכירות",
    "Committee on the Exercise of Inalienable Rights of the Palestinian People :":
      "הוועדה למימוש זכויות בלתי ניתנות לביטול של העם הפלסטיני",
    "Peaceful settlement of the Question of Palestine :":
      "הסדר שלום בשאלת פלסטין",
    "Special Information Programme on the Question of Palestine of the Department of Public Information of the Secretariat :":
      "תוכנית מידע מיוחדת בשאלת פלסטין של המחלקה להסברה של המזכירות",
    "Special Information Programme on question of Palestine of the Department of Public Information of the Secretariat :":
      "תוכנית מידע מיוחדת בנושא פלסטין של המחלקה להסברה של המזכירות",
    "Status of Palestine in the United Nations :":
      "מעמדה של פלסטין באו\"ם",
      "Special information programme on the question of Palestine of the Department of Global Communications of the Secretariat  :": 'תכנית הסברה מיוחדת בשאלת פלסטין של המחלקה לתקשורת גלובלית של המזכירות',
      "Status of the Occupied Territory, including East Jerusalem :": 'מעמד השטח הכבוש, כולל מזרח ירושלים',
      "Question of Palestine : Department of Public Information of the Secretariat :": 'שאלת פלסטין: המחלקה להסברה של המזכירות',
      "Question of Palestine : Committee on the Exercise of the Inalienable Rights of the Palestinian People :": 'הוועדה למימוש הזכויות הבלתי ניתנות לביטול של העם הפלסטיני',
      "Pro Israel Votes": 'הצבעות בעד ישראל',
      "Anti-Israel votes":'הצבעות נגד ישראל',
      "Neutral votes":"הצבעות ניטרליות",
      "Date of last vote":"תאריך הצבעה אחרונה",
      "In the last vote the state":"בהצבעה האחרונה המדינה",
      "List of countries":"רשימת המדינות",
      " voted against Israel":" הצביעה נגד ישראל",
      " avoided":" נמנעה",
      " voted for Israel": " הצביעה בעד ישראל",
      "Summary charts": "גרפים מסכמים",
      "About": "אודות",
      "Pro Israel":"בעד ישראל",
      "Anti-Israel":"נגד ישראל",
      "Neutral":"נטרלי",
      "Votes":"הצבעות",
      "history by date1":"הסטוריית ההצבעות של ",
      "history by date2":" לפי תאריך",
      'trnslate':'En',
      'Sort by support for Israel':'מיין לפי תמיכה בישראל',
      'Sort by thousand byte':'מיין לפי סדר מילוני',
      about1: 'שיטת עבודה',
      about2: 'לקחתי מתוך אתר האו"ם את רשימת ההצבעות לפי פילטור "פלסטין" רשימת ההצבעות הן:',
      about3: 'לא לקחתי את הצבעות של מועצת הביטחון אלא רק הצבעות פתוחות לכלל המדינות, כיוון שמטרת הפרוייקט הוא להראות את מעמד וחברות ישראל עם המדינות השונות, ולא עם החברות הבודדות של מועצת הביטחון.',
      about4: 'יצאתי מנקודת הנחה שתמיד ישראל מצביעה בעד עצמה, ולכן ההגדרה להצבעה בעד ישראל היא להצביע כמו ישראל. יש לכל מדינה בכל הצבעה 5 אפשרויות - כן, לא, ונטרלי. כל אחת מהן זאת הצבעה אקטיבית. וכן מדינה שלא קיימת כמו מזרח גרמניה, שלא נספרת, ואפשרות נוספת של מדינה ששקיימת אבל לא מצביעה. לדוגמא אפגניסטן במעמד הזה כרגע, ואני מתייחס לזה כמו למדינה שלא קיימת.',
      about5: 'דרכי יצירת קשר',
      about6: 'שמי אברהם בן ארוש',
      about7: 'מייל: ',
      about8: 'לינקדאין: '

  },
};
